In [2]:
## import libraries
import pandas as pd

In [3]:
## import data
assessed_df = pd.read_excel('input/1_AC Property Assessments_20260714.xlsx',dtype={'PROPERTYHOUSENUM':object,
'PROPERTYFRACTION':object,
'PROPERTYZIP':object,
'MUNICODE':object,
'TAXYEAR':object,
'SCHOOLCODE':object,
'NEIGHCODE':object,
'TAXCODE':object,
'OWNERCODE':object,
'USECODE':object,
'SALECODE':object,
})

## Clean data

In [4]:
## change column names to lowercase
assessed_df.columns = assessed_df.columns.str.lower()

In [5]:
## change sale date to datetime datatype
assessed_df['saledate'] = assessed_df['saledate'].astype('datetime64[ns]')

In [6]:
## create a new column for sale year
assessed_df['sale_yr']=assessed_df['saledate'].dt.year

In [7]:
## strip muni names of whitespace
assessed_df['munidesc'] = assessed_df['munidesc'].str.strip()

In [8]:
## check number of rows in original dataset
len(assessed_df)

584925

In [9]:
## check number of munis in original dataset
assessed_df.munidesc.nunique()

175

## Filtering for recent, valid, taxable sales

Some experts have advised me to limit the dataset to 2025 and 2026 to avoid a high frequency of properties where values have been appealed, while others have said to choose a broader timeframe and in turn caste a wider net. I've chosen to include sales between 2024 and 2026 as a compromise between these two competing lines of thought.

In [10]:
## filter data for sales completed between 2024 and 2026
sales_24_26 = assessed_df[(assessed_df['sale_yr'] >= 2024) & (assessed_df['sale_yr'] <= 2026)]

In [11]:
## checking the length of the filtered dataset
len(sales_24_26)

67833

In [12]:
## filter for taxable parcels
taxable_24_26 = sales_24_26[sales_24_26['taxcode'] == 'T']

In [13]:
## check new length after filtering for taxable parcels
len(taxable_24_26)

66761

In [14]:
## check number of munis after filtering for taxable parcels between 2024-26
taxable_24_26.munidesc.nunique()

175

No parcels with sale codes of 'U' or 'UR' are included in the dataset. I learned this in hindsight after trying to filter for them. The Allegheny County OPA lists U, UR, and O as the codes for valid sales.

In [15]:
## filter for valid sales
valid_24_26 = taxable_24_26[taxable_24_26['salecode'].isin([0,'U','UR'])]

In [16]:
## check the new length
len(valid_24_26)

21506

In [17]:
## check the new number of unique munis
valid_24_26['munidesc'].nunique()

171

The International Association of Assessing Officers recommends having at least 15 sales to observe per sample. Other experts, such as CMU Professor Robert Strauss, suggest including at least 30 sales per sample. 

I'm going to stick with IAAO's recommendation, mostly because I want to analyze the data at the municipal level rather than the school district level, which would yield more samples per district, but less granularity.

In [18]:
## grouping the latest dataset according to municipality, then sorting from greatest number of sales to least.
## looking at the tail-end of the data to see which munis have fewer than 15 sales
not_observable = valid_24_26['munidesc'].value_counts().tail(24).reset_index()
not_observable

                   munidesc  count
0              Glen Osborne     14
1      3rd Ward  - DUQUESNE     14
2                   Kilbuck     13
3           East Pittsburgh     13
4         Sewickley Heights     13
5   10th Ward -  McKEESPORT     11
6                  Chalfant     11
7             Rosslyn Farms     10
8                   Lincoln      8
9                    Frazer      8
10                     Wall      8
11                 Braddock      7
12                   Rankin      7
13                Thornburg      7
14     2nd Ward  - DUQUESNE      7
15                 McDonald      5
16         Ben Avon Heights      5
17           West Elizabeth      4
18         South Versailles      3
19                Haysville      2
20                Glenfield      1
21                 Trafford      1
22   6th Ward  - McKEESPORT      1
23   5th Ward  - McKEESPORT      1

In [19]:
## make a list of just the muni names
not_obv_list = not_observable['munidesc'].tolist()

In [21]:
## how many additional munis will we have to exclude from the analysis?
len(not_obv_list)

24

In [22]:
## choosing all munis EXCEPT the ones listed above
valid_df = valid_24_26[~valid_24_26['munidesc'].isin(not_obv_list)]

In [23]:
## look at length of the dataset
len(valid_df)

21332

In [24]:
## what was the overall median sales price?
valid_df.saleprice.median()

np.float64(265000.0)

In [25]:
## checking new number of unique munis
valid_df.munidesc.nunique()

147

## Create separate CSVs for three example neighborhoods
Upper Lawrenceville (10th ward), Wilkinsburg, Findlay Township

In [26]:
## 10th ward
ward_10 = valid_df[valid_df['munidesc']=='10th Ward - PITTSBURGH']
ward_10.to_csv('output/ward_10.csv')

In [27]:
## wilkinsburg
wilkins = valid_df[valid_df['munidesc']=='Wilkinsburg']
wilkins.to_csv('output/wilkinsburg.csv')

In [28]:
## findlay twp
findlay = valid_df[valid_df['munidesc']=='Findlay']
findlay.to_csv('output/findlay.csv')

## Findlay

In [62]:
## how many properties in Findlay Township sold between 24-26?
len(findlay)

136

In [74]:
## how many properties sold between 24-26 were built after 2013?
post_2013 = findlay[findlay['yearblt'] > 2013]
len(post_2013)

54

In [76]:
## percentage built post-2013
54/136

0.39705882352941174

## Ward 10

In [45]:
## what was the median sales price for ward 10?
ward_10.saleprice.median()

np.float64(325000.0)

In [51]:
ward_10.head()

,parid,propertyowner,propertyhousenum,propertyfraction,propertyaddress,propertycity,propertystate,propertyunit,propertyzip,municode,...,heatingcooling,heatingcoolingdesc,fireplaces,bsmtgarage,finishedlivingarea,cardnumber,alt_id,taxyear,asofdate,sale_yr
20215,0050J00038000000,NGUYEN HUE,4807,,DEARBORN ST,PITTSBURGH,PA,,15224,110,...,2,Central Heat,0.0,0.0,1404.0,1.0,NaN,2026,2026-07-14,2024.0
20257,0050K00196000000,BANGIOLO LOIS J,127,,N MILLVALE AVE,PITTSBURGH,PA,,15224,110,...,B,Central Heat with AC,0.0,0.0,1428.0,1.0,NaN,2026,2026-07-14,2024.0
21341,0080H00063000000,LEWISBROTHERS0412 LLC,5202,,KEYSTONE ST,PITTSBURGH,PA,,15201,110,...,2,Central Heat,0.0,0.0,1860.0,1.0,NaN,2026,2026-07-14,2024.0
21347,0080H00224000000,OSTEN JEREMY,802,,MCCANDLESS AVE,PITTSBURGH,PA,,15201,110,...,B,Central Heat with AC,0.0,0.0,1460.0,1.0,NaN,2026,2026-07-14,2026.0
21376,0080D00337000000,MILLER STEPHANIE,5312,,HOLMES ST,PITTSBURGH,PA,,15201,110,...,B,Central Heat with AC,0.0,0.0,1520.0,1.0,NaN,2026,2026-07-14,2025.0

In [72]:
## how many sales for all of ward 10?
len(ward_10)

261

In [71]:
## how many built post-2013?
ward_10_post_2013 = ward_10[ward_10['yearblt']>2013]
len(ward_10_post_2013)

18

In [73]:
## percentage of sales that were for properties built after 2013
18/261

0.06896551724137931

In [54]:
## finding sale ratio for properties in Ward 10
ward_10['ratio'] = ward_10['fairmarkettotal']/ward_10['saleprice']

/var/folders/09/dth632p523n1dk0qt7d74bsr0000gn/T/ipykernel_91756/4069006740.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ward_10['ratio'] = ward_10['fairmarkettotal']/ward_10['saleprice']

In [58]:
## what's the median sales ratio in Ward 10?
ward_10.ratio.median()

np.float64(0.3822950819672131)

In [59]:
## How many times higher are sales prices compared to county-calculated market values?
ward_10['saleprice'].sum()/ward_10['fairmarkettotal'].sum()

np.float64(2.4213804272634794)

In [48]:
## how many homes have sold along Chislett Street?
chislett_df = ward_10[ward_10['propertyaddress']=='CHISLETT ST']
len(chislett_df)

13

In [52]:
## finding sale ratios for homes along chislett st
chislett_df['ratio'] = chislett_df['fairmarkettotal']/chislett_df['saleprice']

/var/folders/09/dth632p523n1dk0qt7d74bsr0000gn/T/ipykernel_91756/202534805.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chislett_df['ratio'] = chislett_df['fairmarkettotal']/chislett_df['saleprice']

In [53]:
## what's the median sales ratio along chislett street?
chislett_df.ratio.median()

np.float64(0.301)

## Which homes have the greatest difference between their property assessments and sales prices?

In [29]:
## create a new column that equals the ratio of assessed values to sales prices
valid_df['ratio'] = valid_df['fairmarkettotal']/valid_df['saleprice']

/var/folders/09/dth632p523n1dk0qt7d74bsr0000gn/T/ipykernel_91756/2953436989.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  valid_df['ratio'] = valid_df['fairmarkettotal']/valid_df['saleprice']

This median sales ratio for this sample is relatively close to [STEB's determination](https://dced.pa.gov/download/common-level-ratio-2025/?wpdmdl=129658&refresh=6a0dccda0a7f91779289306) of the county's CLR, which is 49.3 for 2025.

In [30]:
## find the median ratio for the entire sample
sample_ratio = valid_df['ratio'].median()
sample_ratio

np.float64(0.5012012065707505)

In [31]:
## find the median sales ratio per municipality
muni_median = valid_df.groupby('munidesc')['ratio'].median().reset_index()

From IAAO's [guidelines on sales ratio studies](https://www.iaao.org/wp-content/uploads/StandardonRatioStudies_Exposure-Mar2026.pdf): "While the target level of valuation should be 1.00, a valuation level between 0.90 and 1.10 is considered acceptable for any class of property."

In [32]:
## sort the median ratios highest to lowest
muni_median.sort_values(by='ratio',ascending=False).head(20)

                   munidesc     ratio
13   1st Ward  - PITTSBURGH  0.654464
9    17th Ward - PITTSBURGH  0.604817
26    2nd Ward - PITTSBURGH  0.603393
74                  Findlay  0.600246
59                  Collier  0.561547
112                    Pine  0.558957
57                 Cheswick  0.558890
104           North Fayette  0.554737
111       Pennsbury Village  0.552207
89                  Kennedy  0.549456
136              Versailles  0.545600
93                 Marshall  0.545417
69           Elizabeth Boro  0.541379
82                   Harmar  0.540351
119                Robinson  0.539615
129          Springdale Twp  0.539070
123         Sewickley Hills  0.538631
109                    Ohio  0.536514
90                     Leet  0.536362
67                 Edgewood  0.535669

In [33]:
## create a new column that is the ratio of the muni's ratio to the county's
muni_median['sample_comparison'] = muni_median['ratio']/sample_ratio

In [34]:
muni_median.sort_values(by='sample_comparison',ascending=False)

                  munidesc     ratio  sample_comparison
13  1st Ward  - PITTSBURGH  0.654464           1.305790
9   17th Ward - PITTSBURGH  0.604817           1.206735
26   2nd Ward - PITTSBURGH  0.603393           1.203894
74                 Findlay  0.600246           1.197615
59                 Collier  0.561547           1.120402
..                     ...       ...                ...
10  18th Ward - PITTSBURGH  0.387429           0.773000
32   5th Ward - PITTSBURGH  0.386863           0.771871
0   10th Ward - PITTSBURGH  0.382295           0.762758
19  24th Ward - PITTSBURGH  0.382000           0.762169
5   13th Ward - PITTSBURGH  0.340213           0.678795

[147 rows x 3 columns]

In [35]:
## save to a csv
muni_ratio_comparison = muni_median.sort_values(by='sample_comparison',ascending=False)
muni_ratio_comparison.to_csv('output/muni_ratio_2426_102326.csv')

## Finding COD

In [36]:
## defining a function that will find the cod per muni
def cod(ratios): 
    median_ratio = ratios.median() 
    aad = (ratios - median_ratio).abs().mean() 
    return (aad / median_ratio) * 100

In [37]:
## group by neighborhood, apply the function
cod_by_nhood = valid_df.groupby('munidesc')['ratio'].apply(cod)

Blighted property defined by IAAO: A market area, neighborhood, or region may be defined as blighted if enough blighted properties exist to alter the functioning of the market due to declining economic conditions and social issues.

When considering COD, the IAAO treats distressed/blighted areas -- or places where "Arm’s Length transactions will have more dispersion in their sale ratios because the market is not as defined" -- differently than non-distressed/blighted areas. 

As a result, the COD standards for these areas covers a broader range (10 to 35, generally) than for others (5 to 15).

In [77]:
cod_by_muni = cod_by_nhood.sort_values(ascending=False).reset_index()
cod_by_muni.head()

                 munidesc      ratio
0  27th Ward - PITTSBURGH  89.874786
1  13th Ward - PITTSBURGH  59.397418
2  12th Ward - PITTSBURGH  46.095099
3            Turtle Creek  41.175484
4          Elizabeth Boro  40.995499

In [81]:
len(cod_by_muni)

147

In [80]:
## how many municipalities' COD is higher than 15? 
higher_than_15 = cod_by_muni[(cod_by_muni['ratio'] > 15)]
len(higher_than_15)

94

In [40]:
## save to a CSV
cod_by_muni.to_csv('output/cod_by_muni_20261023.csv')